---
title: "Distribution map"
format: html
---

```{r}
#| echo: false
#| output: false
#| warning: false


library(tidyverse)
library(leaflet)
library(htmlwidgets)
library(crosstalk)
library(bslib)
library(bsicons)
library(summarywidget)
```

``` {r}
#| echo: false
#| output: false

#READ DISTRBUTION DATA
asop <- read.csv("Asopinae_Analises_R_Preparado.csv", sep = ",")
asop <- asop %>%
  na.omit(asop) 
colnames(asop) <- c("Genus", "Species", "X_Longitude", "Y_Latitude", "Country", "Continent", "Realm")

asop$X_Longitude <- as.numeric(asop$X_Longitude) 
asop$Y_Latitude <- as.numeric(asop$Y_Latitude)

row.names(asop) <- NULL

shared_asop <- SharedData$new(asop, group = "Asop")

share_species <- asop %>%
  select(Species) %>%
  unique() %>%
  SharedData$new(group = "Asop")
```

This is the current database of "Asopinae of the World" accessible through an interactive map!



``` {r}
#| echo: false
bscols(
  value_box(
    title = "Records",
    value = summarywidget(shared_asop),
    showcase = bsicons::bs_icon("search"),
    theme = value_box_theme(bg = "#756AB6", fg = "#F3EEEA"),
    width = 0.1
  ),
  
    value_box(
    title = "Species",
    value = summarywidget(share_species),
    showcase = bsicons::bs_icon("search"),
    theme = value_box_theme(bg = "#756AB6", fg = "#F3EEEA"),
    width = 0.1
  )
  
)
```


```{r}
#| echo: false

bscols(
  filter_select("Genus", "Genus", shared_asop, ~Genus),
  filter_select("Species", "Species", shared_asop, ~Species)
  #filter_select("Continent")
  #filter_select("Country")
  #filter_select("Biogeographical Realm")
)

```





```{r}
#| echo: false
#| warning: false

pal <- colorFactor("Spectral", domain = unique(asop$Species))

leaflet(data = shared_asop) %>%
  addProviderTiles("Esri.WorldImagery", group = "Aerial") %>%
  addProviderTiles(providers$CartoDB.Voyager, group = "Default") %>%
  addLayersControl(
    baseGroups = c("Default", "Aerial"),
    options = layersControlOptions(collapsed = T)
    ) %>%
  addCircleMarkers(radius = 2,
                   lng = ~ X_Longitude,
                   lat = ~ Y_Latitude,
                   popup = ~Species,
                   color = ~pal(Species))
```

