---
title: "Raw Data"
format: html
editor: visual
---


```{r load data, message = FALSE, warning = FALSE, include = FALSE}
library(tidyverse)
library(leaflet)
library(htmlwidgets)
library(htmltools)
library(crosstalk)
library(bslib)
library(bsicons)
library(summarywidget)
library(reactable)
```

```{r}
#| echo: false
#| output: false

#READ DISTRBUTION DATA
asop <- read.csv("Asopinae_Analises_R_Preparado.csv", sep = ",")
asop <- asop %>%
  na.omit(asop) 
colnames(asop) <- c("Genus", "Species", "X_Longitude", "Y_Latitude", "Country", "Continent", "Ecoregion", "Realm")

asop$X_Longitude <- as.numeric(asop$X_Longitude) 
asop$Y_Latitude <- as.numeric(asop$Y_Latitude)

row.names(asop) <- NULL


shared_asop <- SharedData$new(asop, group = "Asop")

share_species <- asop %>%
  select(Species) %>%
  unique() %>%
  SharedData$new(group = "Asop")
```

This is the current database of "Asopinae of the World". Here, you can look at the table data.

```{r}
#| echo: false
#| output: false
bscols(
  value_box(
    title = "Records",
    value = summarywidget(shared_asop),
    showcase = bsicons::bs_icon("search"),
    theme = value_box_theme(bg = "#756AB6", fg = "#F3EEEA"),
    width = 0.1
  ),
  
    value_box(
    title = "Species",
    value = summarywidget(share_species),
    showcase = bsicons::bs_icon("search"),
    theme = value_box_theme(bg = "#756AB6", fg = "#F3EEEA"),
    width = 0.1
  )
  
)
```

```{r}
#| echo: false
#| output: false

bscols(
  filter_select("Genus", "Genus", shared_asop, ~Genus),
  filter_select("Species", "Species", shared_asop, ~Species)
  #filter_select("Continent")
  #filter_select("Country")
  #filter_select("Biogeographical Realm")
)

```

```{r}
#| echo: false
#| output: false

library(fontawesome)

htmltools::browsable(
    tagList(
      tags$button(
        tagList(fontawesome::fa("download"), "Download as CSV"),
        onclick = "Reactable.downloadDataCSV('asop_table','Asopinae_Analises_R_Preparado.csv')"
      ),
    reactable(shared_asop,
              defaultColDef = colDef(
                  align = "center",
                  headerStyle = list(background = "#f7f7f8")
                ),
              elementId = 'asop_table')
  )
)
  

```

We also provide a raw data, with the original references, which was included as Supplementary Material 1 of our published article.
